<?php
// Rhymix System Configuration
return array(
	'config_version' => '2.0',
	'db' => array(
		'master' => array(
			'type' => 'mysql',
			'host' => 'localhost',
			'port' => '3306',
			'user' => 'root',
			'pass' => '123456',
			'database' => 'RHYMIX',
			'prefix' => 'rx_',
			'charset' => 'utf8mb4',
			'engine' => 'innodb',
		),
	),
	'cache' => array(
		'truncate_method' => 'delete',
	),
	'ftp' => array(
		'host' => 'localhost',
		'port' => 21,
		'path' => NULL,
		'user' => NULL,
		'pass' => NULL,
		'pasv' => true,
		'sftp' => false,
	),
	'crypto' => array(
		'encryption_key' => 'EfO5EYgVUZFHTM72t2d7nuVLteYNf6kzTL3JOq1U6cNoSA4U7fIqNcqy9RyFXp6r',
		'authentication_key' => '0FzOPaQwhskToHotzj2DwADTfIN2bTpOF1D8JgoVz8NVa43FH2CaC2UawcMED3bO',
		'session_key' => 'orqdZXd1TPEAjZyjDYNgcxmdGLRYVQw8LDr7PGSPT1lRUo9hYH9H0MoSzGrX8gzg',
	),
	'locale' => array(
		'default_lang' => 'ko',
		'enabled_lang' => array(
			'ko',
		),
		'auto_select_lang' => false,
		'default_timezone' => 'Asia/Seoul',
		'internal_timezone' => 32400,
	),
	'url' => array(
		'default' => 'http://localhost/',
		'unregistered_domain_action' => 'redirect_301',
		'http_port' => NULL,
		'https_port' => NULL,
		'ssl' => 'none',
	),
	'session' => array(
		'delay' => false,
		'use_db' => false,
		'use_keys' => false,
		'use_ssl' => false,
		'use_ssl_cookies' => false,
		'domain' => NULL,
		'path' => NULL,
		'lifetime' => 0,
		'refresh' => 300,
	),
	'file' => array(
		'folder_structure' => 2,
		'umask' => '0000',
	),
	'mail' => array(
		'type' => 'mailfunction',
	),
	'view' => array(
		'manager_layout' => 'module',
		'minify_scripts' => 'common',
		'concat_scripts' => 'none',
		'server_push' => false,
		'use_gzip' => false,
	),
	'admin' => array(
		'allow' => array(),
		'deny' => array(),
	),
	'lock' => array(
		'locked' => false,
		'title' => 'Maintenance',
		'message' => '',
		'allow' => array(),
	),
	'debug' => array(
		'enabled' => true,
		'log_slow_queries' => 0,
		'log_slow_triggers' => 0,
		'log_slow_widgets' => 0,
		'log_slow_remote_requests' => 0,
		'log_filename' => NULL,
		'display_type' => array(
			'comment',
		),
		'display_content' => array(),
		'display_to' => 'admin',
		'write_error_log' => 'fatal',
		'allow' => array(),
	),
	'seo' => array(
		'main_title' => '',
		'subpage_title' => '',
		'document_title' => '',
		'og_enabled' => false,
		'og_extract_description' => false,
		'og_extract_images' => false,
		'og_extract_hashtags' => false,
		'og_use_timestamps' => false,
	),
	'mediafilter' => array(
		'iframe' => array(),
		'object' => array(),
		'classes' => array(),
	),
	'security' => array(
		'check_csrf_token' => false,
		'nofollow' => false,
	),
	'mobile' => array(
		'enabled' => true,
		'tablets' => false,
		'viewport' => 'width=device-width, initial-scale=1.0, user-scalable=yes',
	),
	'use_prepared_statements' => true,
	'use_rewrite' => false,
	'use_sso' => false,
	'other' => array(),
);
