<?php

// DO NOT EDIT THIS FILE. CHANGES WILL NOT BE APPLIED.
// TO CHANGE RHYMIX SYSTEM CONFIGURATION, EDIT config.php INSTEAD.

$db_info = (object)array(
	'master_db' => array(
		'db_type' => 'mysql_innodb',
		'db_hostname' => 'localhost',
		'db_port' => '3306',
		'db_userid' => 'root',
		'db_password' => '123456',
		'db_database' => 'RHYMIX',
		'db_table_prefix' => 'rx_',
		'db_charset' => 'utf8mb4',
	),
	'slave_db' => array(
		array(
			'db_type' => 'mysql_innodb',
			'db_hostname' => 'localhost',
			'db_port' => '3306',
			'db_userid' => 'root',
			'db_password' => '123456',
			'db_database' => 'RHYMIX',
			'db_table_prefix' => 'rx_',
			'db_charset' => 'utf8mb4',
		),
	),
	'use_object_cache' => NULL,
	'lang_type' => 'ko',
	'time_zone' => '+0900',
	'delay_session' => 'N',
	'use_db_session' => 'N',
	'minify_scripts' => 'Y',
	'admin_ip_list' => NULL,
	'use_sitelock' => 'N',
	'sitelock_title' => 'Maintenance',
	'sitelock_message' => '',
	'sitelock_whitelist' => array(
		'127.0.0.1',
	),
	'embed_white_iframe' => NULL,
	'embed_white_object' => NULL,
	'use_mobile_view' => 'Y',
	'use_prepared_statements' => 'Y',
	'use_rewrite' => 'N',
	'use_sso' => 'N',
);
