<?php

// DO NOT EDIT THIS FILE. CHANGES WILL NOT BE APPLIED.
// TO CHANGE RHYMIX SYSTEM CONFIGURATION, EDIT config.php INSTEAD.

$ftp_info = (object)array(
	'ftp_host' => 'localhost',
	'ftp_port' => 21,
	'ftp_user' => NULL,
	'ftp_pasv' => 'Y',
	'ftp_root_path' => NULL,
	'sftp' => 'N',
);
